### ISSUE TITLE
More than two people in call

### ISSUE THREAD

**Issue by The-Code-Monkey** [nguymin4/react-videocall#5]
How do i make it so there can be more than one people looking at a call

**Comment by nguymin4** [comment]
Basically,
- You need a button inside calling mode which allow you to add new person.
- Then add a new <video> to display the video from the new people.

Sounds simple, but I think it will take time.

**Comment by The-Code-Monkey** [comment]
would it work though as i have no clue about node servers we normally run php but for this client we need this video functionality

**Comment by nguymin4** [comment]
This new feature should be 100% implemented in front-end side not server side. I also have to admit that I implemented this more than 2 years ago so the code base is outdated. Probably need to rewritten some parts to add this new feature. Unfortunately I don't have much time.

**Comment by The-Code-Monkey** [comment]
If you could point me in the right direction that would be a great help as i have no clue where to start in the docs all i know is that peerConnection is for 1-1 but i cant find anything for more than 2 people

**Comment by nguymin4** [comment]
I think the steps could be (all files are in client/src):
1. Allow to add new friend while you are in middle of the video call.
2. In `app.js` instead of allow only 1 peer connection (`this.pc`) it should be an array (`this.pcs`) and then in the event  `.on('peerStream', src => this.setState({ peerSrc: src }))` the `peerSrc` also should become an array (`this.state.peerSrcs`). After that the `<CallWindow ... />` will receive multiple `peerSrcs`
3. In `CallWindow.js` when you have multiple `this.props.peerSrcs` you will generate multiple `<video>` and arrange it accordingly. Maybe just split the screen in half in desktop mode. In mobile mode you can choose the first one is the primary (user can choose which one is the primary).

The main idea is like that

**Comment by barakjobs** [comment]
Do you have the code for calling to more than 2 people

**Comment by nguymin4** [comment]
Hi barakjobs, unfortunately not. This was my fun project more than 3 years ago so they lacks of many features.

**Comment by barakjobs** [comment]
thanks for quick reply.....
Do you have any screen sharing project in React. can you please help me regarding that. I want to share my screen to another user.

**Comment by nguymin4** [comment]
Unfortunately, I don't have any screen sharing project.
